name: pizza_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.6.1
  firebase_core: ^2.31.0
  path_provider: ^2.1.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.2.1
  html: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - resimler/
